name: Potential Duplicates
description: Search for potential issue duplicates using Damerau–Levenshtein algorithm..
author: bubkoo <bubkoo.wy@gmail.com>
inputs:
  GITHUB_TOKEN:
    description: Your GitHub token for authentication.
    required: true
  label:
    description: Label to set, when potential duplicates are detected.
    default: potential-duplicate
    required: false
  state:
    description: "Get issues with state to compare. Supported state: 'all', 'closed', 'open'"
    default: all
    required: false
  threshold:
    description: Label color to set, when potential duplicates are detected.
    default: 0.6
    required: false
  comment:
    description: Comment to post when potential duplicates are detected.
    default: >
      Potential duplicates: {{#issues}}
        - [#{{ number }}] {{ title }} ({{ accuracy }}%)
      {{/issues}}


    required: false
  reactions:
    description: Reactions to be add to comment when potential duplicates are detected.
    required: false
runs:
  using: node12
  main: dist/index.js
branding:
  icon: type
  color: yellow # gray-dark purple red orange green blue yellow black white
