name: Release
on:
  push:
    branches:
      - master
      - next
      - next-major
      - alpha
      - beta
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️　Checkout
        uses: actions/checkout@v2

      - name: 🚧　Install
        run: yarn install

      - name: 📦　Build
        run: NODE_OPTIONS=--openssl-legacy-provider yarn build

      - name: 📦　Release
        uses: wow-actions/release-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
